name: AWS 배포 자동화

on:
  push:
    branches:
      - main
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: Node 세팅
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'
          cache: 'yarn'

      - name: 의존성 설치
        run: |
          yarn install --frozen-lockfile

      - name: 프로젝트 빌드
        run: |
          yarn build

      - name: 테스트 실행
        run: |
          yarn test

      - name: AWS CLI 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      